export const SEARCH_CLUBS = 'SEARCH_CLUBS';
export const FILTER_CLUBS = 'FILTER_CLUBS';
export const LOAD_ALL_CLUBS = 'LOAD_ALL_CLUBS';
export const LOAD_MORE_CLUBS = 'LOAD_MORE_CLUBS';
export const GET_ORGANIZATION = 'GET_ORGANIZATION';
export const CLEAR_ORGANIZATION = 'CLEAR_ORGANIZATION';
export const CLEAR_ORGANIZATIONS = 'CLEAR_ORGANIZATIONS';
export const LOAD_MORE_ORGS = 'LOAD_MORE_ORGS';
export const SET_FORM_DETAILS = 'SET_FORM_DETAILS';
export const SET_TAGS = 'SET_TAGS';
export const RESET_TAGS = 'RESET_TAGS'
export const RESET_MEMBERS= 'RESET_MEMBERS'
export const SET_MEMBERS = 'SET_MEMBERS'


export const LOAD_PROFILE = 'LOAD_PROFILE';
export const LOAD_PROFILE_NOT_LOGGED_IN = 'LOAD_PROFILE_NOT_LOGGED_IN';
export const LOAD_PROFILE_ERROR = 'LOAD_PROFILE_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const GET_TAGS = 'GET_TAGS';
export const GET_SIZE_TAGS = 'GET_SIZE_TAGS';


export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPLOAD_IMAGES = 'UPLOAD_IMAGES';
export const DELETE_EVENT = 'DELETE_EVENT';
export const ADD_EVENT = 'ADD_EVENT';
export const ADD_RESOURCE = 'ADD_RESOURCE';
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

export const ADD_RECR_EVENT = 'ADD_RECR_EVENT';
export const UPDATE_RECR_EVENT = 'UPDATE_RECR_EVENT';
export const DELETE_RECR_EVENT = 'DELETE_RECR_EVENT';

// Gallery types
export const GET_GALLERY_PHOTOS = 'GET_GALLERY_PHOTOS';
export const ADD_GALLERY_PHOTO = 'ADD_GALLERY_PHOTO';
export const UPDATE_GALLERY_PHOTO = 'UPDATE_GALLERY_PHOTO';
export const DELETE_GALLERY_PHOTO = 'DELETE_GALLERY_PHOTO';

// Student types
export const FINISH_REGISTER = 'FINISH_REGISTER';
export const REFRESH_ACCESS_TOKEN = 'REFRESH_ACCESS_TOKEN';
export const REVOKE_ACCESS_TOKEN = 'REVOKE_ACCESS_TOKEN';
export const REVOKE_REFRESH_TOKEN = 'REVOKE_REFRESH_TOKEN';

export const GET_MAJORS = 'GET_MAJORS';
export const GET_MINORS = 'GET_MINORS';
export const GET_YEARS = 'GET_YEARS';

export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const UPDATE_PROFILE_INFO = 'UPDATE_PROFILE_INFO';
export const ADD_FAVORITE_CLUBS = 'ADD_FAVORITE_CLUBS';
export const DELETE_FAVORITE_CLUBS = 'DELETE_FAVORITE_CLUBS';
export const UPDATE_CLUB_BOARD = 'UPDATE_CLUB_BOARD';
