export const SEARCH_CLUBS = 'SEARCH_CLUBS';

export const USER_LOADED = 'USER_LOADED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const LOGOUT = 'LOGOUT';
