export const SEARCH_CLUBS = 'SEARCH_CLUBS';

export const LOAD_PROFILE = 'LOAD_PROFILE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const LOGOUT = 'LOGOUT';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
